services:
  portfolio:
    build: ./Portfolio
    container_name: portfolio
    ports:
      - 3010:3000
    volumes:
      - ./Portfolio:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  express-app:
    build: ./Api
    container_name: express-portfolio
    ports:
      - "5000:3000"
    volumes:
      - ./Api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  openvscode-server:
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: openvscode-server-portfolio
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CONNECTION_TOKEN= #optional
      - CONNECTION_SECRET= #optional
      - SUDO_PASSWORD=123 #optional
      - SUDO_PASSWORD_HASH= #optional
    volumes:
      - /path/to/openvscode-server/config:/config
      - ./:/workspace/
    ports:
      - 3011:3000
    restart: unless-stopped
